# Generated by Django 4.2.4 on 2023-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
